ALTER TABLE tasks ADD COLUMN IF NOT EXISTS adapter_type VARCHAR(64) NOT NULL DEFAULT 'inline';

ALTER TABLE tasks ADD COLUMN IF NOT EXISTS owner VARCHAR(255);
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS environment VARCHAR(64);

ALTER TABLE workflows ADD COLUMN IF NOT EXISTS owner VARCHAR(255);
ALTER TABLE workflows ADD COLUMN IF NOT EXISTS environment VARCHAR(64);
